---

# Install terraform
terraform_binary_install: true
terraform_binary_version: '0.12.24'
terraform_binary_platform: 'linux_amd64'

# Where to deploy terraform resource files
terraform_config_dir: 'terraform'

# Delete existing resources before deploying new ones
terraform_purge: false

# Which environment we're going to deploy
terraform_cloud_provider: 'azure'

# Azure cloud provider default variables
# Azure storage blob for synchronized tfstate
azure_tfstate_resource_group_name: "terraform-tfstate"
azure_tfstate_resources:
  - provider
  - resource_group
  - storage
  - storage_container
# Azure infrastructure details
azure_subnets:
  - name: subnet_server
    prefix: 192.168.0.0/25
azure_resources:
  - provider
  - resource_group
  - storage
  - network
  - network_sec_group
  - availability_set
azure_vpn_resources:
  - virtualnetwork_gw
  - localnetwork_gw
azure_resource_group_name: "azure-resource-group"
azure_location: ''
azure_subscription_id: ''
azure_client_id: ''
azure_client_secret: ''
azure_tenant_id: ''
azure_network_sec_group_name: 'network_sec_group'
azure_vnet_name: 'vnet'
azure_vnet_addr_space: '192.168.0.0/24'
azure_gw_subnet_name: 'gateway_subnet'
azure_gw_subnet_addr_prefix: '192.168.0.248/29'
azure_storage_account_name: 'mystorageaccount'
azure_vnet_gw_name: 'vnet_gw'
azure_lnet_gw: ''
azure_lnet_gw_name: 'lnet_gw'

# Azure VM default variables
azure_vm_admin_username: 'adminuser'
azure_vm_admin_password: '4dm1n!'
azure_vm_disable_password_authentication: true
# Azure VM image to deploy. By default CentOS 7.7 are used, customize it in
# the inventory group or host variables. The list of images is available via
# 'az vm image list' command.
azure_vm_image:
  publisher: 'OpenLogic'
  offer: 'CentOS'
  sku: '7_7-gen2'
  version: '7.7.2020042901'
