---

- name: "Deploy group {{ group_name }} VMS templates"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "azure/vms.tf.j2", dest: "{{ terraform_config_dir }}/azure/{{ group_name }}.vms.tf" }
    - { src: "azure/disks.tf.j2", dest: "{{ terraform_config_dir }}/azure/{{ group_name }}.disks.tf" }
    - { src: "azure/nics.tf.j2", dest: "{{ terraform_config_dir }}/azure/{{ group_name }}.nics.tf" }
