---

- name: Check if terraform binary is available
  ansible.builtin.command: "{{ terraform_config_dir }}/bin/terraform -version"
  register: terraform_binary_check
  changed_when: false
  failed_when: false

- name: Get terraform binary
  block:
    - name: Install unzip
      ansible.builtin.package:
        name: unzip
        state: present
      become: true
      when: ansible_os_family != "Darwin"

    - name: "Create directory for terraform binary under {{ terraform_config_dir }}"
      ansible.builtin.file:
        path: "{{ terraform_config_dir }}/bin"
        state: directory
        mode: '0750'

    - name: Download and extract terraform binary
      ansible.builtin.unarchive:
        src: "https://releases.hashicorp.com/terraform/{{ terraform_binary_version }}/\
              terraform_{{ terraform_binary_version }}_{{ terraform_binary_platform }}.zip"
        dest: "{{ terraform_config_dir }}/bin"
        remote_src: true
  when:
    - terraform_binary_check.rc != 0 or
      terraform_binary_check.stdout.splitlines()[0] != 'Terraform v' + terraform_binary_version
