---

- name: Check if tf binary is available
  ansible.builtin.command: "{{ tf_config_dir }}/bin/{{ tf_cmd }} -version"
  register: tf_binary_check
  changed_when: false
  failed_when: false

- name: Get tf binary
  block:
    - name: Install unzip
      ansible.builtin.package:
        name: unzip
        state: present
      become: true
      when: ansible_os_family != "Darwin"

    - name: "Create directory for tf binary under {{ tf_config_dir }}"
      ansible.builtin.file:
        path: "{{ tf_config_dir }}/bin"
        state: directory
        mode: '0750'

    - name: Download and extract tf binary
      ansible.builtin.unarchive:
        src: "{{ tf_binary_url }}"
        dest: "{{ tf_config_dir }}/bin"
        remote_src: true
  when:
    - tf_binary_check.rc != 0 or
      not ( tf_binary_check.stdout | regex_search('Terraform v' + tf_binary_version) or
            tf_binary_check.stdout | regex_search('OpenTofu v' + tf_binary_version) )
