---

- name: Install terraform locally
  ansible.builtin.include_tasks: install.yml
  when:
    - terraform_binary_install | bool

- name: "Create local configurations directory {{ terraform_config_dir }}"
  ansible.builtin.file:
    path: "{{ terraform_config_dir }}"
    state: directory
    mode: '0750'

- name: Deploy Azure environment
  ansible.builtin.include_tasks: azure.yml
  when:
    - terraform_cloud_provider == 'azure'

- name: Deploy Libvirt environment
  ansible.builtin.include_tasks: libvirt.yml
  when:
    - terraform_cloud_provider == 'libvirt'
