---

- name: Install tf cmd locally
  ansible.builtin.include_tasks: install.yml
  when:
    - tf_binary_install | bool

- name: "Create local configurations directory {{ tf_config_dir }}"
  ansible.builtin.file:
    path: "{{ tf_config_dir }}"
    state: directory
    mode: '0750'

- name: Deploy Azure environment
  ansible.builtin.include_tasks: azure.yml
  when:
    - tf_cloud_provider == 'azure'

- name: Deploy Libvirt environment
  ansible.builtin.include_tasks: libvirt.yml
  when:
    - tf_cloud_provider == 'libvirt'
