---

- name: Create Azure private output directory
  file:
    path: "{{ terraform_config_dir }}/azure-private"
    state: directory
    mode: 0700

- name: Deploy Azure private variables source templates
  template:
    src: "azure/variables.source.j2"
    dest: "{{ terraform_config_dir }}/azure-private/variables.source"
    mode: 0600

- name: Generate ssh RSA public/private key
  command:
    cmd: ssh-keygen -t rsa -N '' -f azure_id_rsa
    chdir: "{{ terraform_config_dir }}/azure-private"
    creates: azure_id_rsa.pub
  when:
    - not azure_vm_admin_ssh_public_key_file is defined
    - azure_vm_disable_password_authentication | bool

- name: Set the ssh RSA public key fact
  set_fact:
    azure_vm_admin_ssh_public_key_file: "{{ terraform_config_dir }}/azure-private/azure_id_rsa.pub"
  when:
    - not azure_vm_admin_ssh_public_key_file is defined

- block:
    - name: Purge azure-init output directory
      file:
        path: "{{ terraform_config_dir }}/azure-init"
        state: absent
      when:
        - terraform_purge | bool

    - name: Create azure-init output directory
      file:
        path: "{{ terraform_config_dir }}/azure-init"
        state: directory

    - name: Deploy resources templates
      template:
        src: "azure/{{ item }}.tf.j2"
        dest: "{{ terraform_config_dir }}/azure-init/{{ item }}.tf"
      with_items:
        - "{{ azure_tfstate_resources }}"
      vars:
        skip_azure_backend: true
        azure_resource_group_name: "{{ azure_tfstate_resource_group_name }}"
        azure_storage_account_name: "{{ terraform_tfstate_on_azure_storage_container }}"
        azure_storage_container_name: "{{ terraform_tfstate_on_azure_storage_container }}"
  when:
    - terraform_tfstate_on_azure_storage_container is defined

- name: Purge azure output directory
  file:
    path: "{{ terraform_config_dir }}/azure"
    state: absent
  when:
    - terraform_purge | bool

- name: Create Azure output directory
  file:
    path: "{{ terraform_config_dir }}/azure"
    state: directory

- name: Deploy Azure general resources templates
  template:
    src: "azure/{{ item }}.tf.j2"
    dest: "{{ terraform_config_dir }}/azure/{{ item }}.tf"
  with_items:
    - "{{ azure_resources }}"

- name: Deploy Azure VPN resources templates
  template:
    src: "azure/{{ item }}.tf.j2"
    dest: "{{ terraform_config_dir }}/azure/{{ item }}.tf"
  with_items:
    - "{{ azure_vpn_resources }}"
  when:
    - azure_localnetworkgws is defined

- name: Deploy Azure key vault template
  template:
    src: "azure/key_vault.tf.j2"
    dest: "{{ terraform_config_dir }}/azure/key_vault.tf"
  when:
    - azure_key_vault_enable | bool

- name: Deploy Azure virtual machines specific templates
  template:
    src: azure/vms.tf.j2
    dest: "{{ terraform_config_dir }}/azure/vms_{{ group.key }}.tf"
  with_dict:
    - "{{ groups }}"
  loop_control:
    loop_var: group
  when:
    - group.key not in (azure_vms_excluded_groups)

- name: Display a reminder for sourcing variables
  debug:
    msg:
      - "Remember to import the variable file in order to tell Terraform which"
      - "subscription use during the run. Before run Terraform, please execute:"
      - "    source {{ terraform_config_dir }}/azure-private/variables.source"
