---

- name: Include a subnet list as a var file
  include_vars:
    file: roles/terraform_confs/vars/subnet_list.yml

- name: Include a local network gateway list as a var file
  include_vars:
    file: inventory/mobyt/vars/localnetworkgw_list.yml

- name: Deploy Variables template
  template:
    src: variables.tf.j2
    dest: /home/ansible/terraform/variables.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Provider template
  template:
    src: provider.tf.j2
    dest: /home/ansible/terraform/provider.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Resource Group template
  template:
    src: resource_group.tf.j2
    dest: /home/ansible/terraform/resource_group.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Storage Account template
  template:
    src: storage.tf.j2
    dest: /home/ansible/terraform/storage.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Network template
  template:
    src: network.tf.j2
    dest: /home/ansible/terraform/network.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Network Security Rule template
  template:
    src: network_sec_group.tf.j2
    dest: /home/ansible/terraform/network_sec_group.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Virtual Network Gateway template
  template:
    src: virtualnetwork_gw.tf.j2
    dest: /home/ansible/terraform/virtualnetwork_gw.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Local Network Gateway template
  template:
    src: localnetwork_gw.tf.j2
    dest: /home/ansible/terraform/localnetwork_gw.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Availability Set
  template:
    src: availability_set.tf.j2
    dest: /home/ansible/terraform/availability_set.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Apache template
  template:
    src: apache.tf.j2
    dest: /home/ansible/terraform/apache.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy HAProxy template
  template:
    src: haproxy.tf.j2
    dest: /home/ansible/terraform/haproxy.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Nginx template
  template:
    src: nginx.tf.j2
    dest: /home/ansible/terraform/nginx.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Appserver template
  template:
    src: appserver.tf.j2
    dest: /home/ansible/terraform/appserver.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Redis template
  template:
    src: redis.tf.j2
    dest: /home/ansible/terraform/redis.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Elastic template
  template:
    src: elastic.tf.j2
    dest: /home/ansible/terraform/elastic.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy MySQL template
  template:
    src: mysql.tf.j2
    dest: /home/ansible/terraform/mysql.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy RabbitMQ template
  template:
    src: rabbitmq.tf.j2
    dest: /home/ansible/terraform/rabbitmq.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Zabbix Proxy template
  template:
    src: zabbixproxy.tf.j2
    dest: /home/ansible/terraform/zabbixproxy.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Kannel Proxy template
  template:
    src: kannel.tf.j2
    dest: /home/ansible/terraform/kannel.tf
    owner: root
    group: root
    mode: 0644
