---

- name: Deploy Variables template
  template:
    src: variables.tf.j2
    dest: variables.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Provider template
  template:
    src: provider.tf.j2
    dest: provider.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Resource Group template
  template:
    src: resource_group.tf.j2
    dest: resource_group.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Storage Account template
  template:
    src: storage.tf.j2
    dest: resource_group.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Frontend template
  template:
    src: frontend.tf.j2
    dest: frontend.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Network template
  template:
    src: network.tf.j2
    dest: network.tf
    owner: root
    group: root
    mode: 0644

- name: Deploy Network Security Rule template
  template:
    src: network_sec_group.tf.j2
    dest: network_sec_group.tf
    owner: root
    group: root
    mode: 0644
