---

- name: Include a subnet list as a var file
  include_vars:
    file: roles/terraform_confs/vars/subnet_list.yml

- name: Include a local network gateway list as a var file
  include_vars:
    file: inventory/mobyt/vars/localnetworkgw_list.yml

- name: Deploy Variables template
  template:
    src: variables.tf.j2
    dest: "{{ terraform_output_dir }}/variables.tf"
    owner: root
    group: root
    mode: 0644

- name: Deploy Provider template
  template:
    src: provider.tf.j2
    dest: "{{ terraform_output_dir }}/provider.tf"
    owner: root
    group: root
    mode: 0644

- name: Deploy Resource Group template
  template:
    src: resource_group.tf.j2
    dest: "{{ terraform_output_dir }}/resource_group.tf"
    owner: root
    group: root
    mode: 0644

- name: Deploy Storage Account template
  template:
    src: storage.tf.j2
    dest: "{{ terraform_output_dir }}/storage.tf"
    owner: root
    group: root
    mode: 0644

- name: Deploy Network template
  template:
    src: network.tf.j2
    dest: "{{ terraform_output_dir }}/network.tf"
    owner: root
    group: root
    mode: 0644

- name: Deploy Network Security Rule template
  template:
    src: network_sec_group.tf.j2
    dest: "{{ terraform_output_dir }}/network_sec_group.tf"
    owner: root
    group: root
    mode: 0644

- name: Deploy Virtual Network Gateway template
  template:
    src: virtualnetwork_gw.tf.j2
    dest: "{{ terraform_output_dir }}/virtualnetwork_gw.tf"
    owner: root
    group: root
    mode: 0644

- name: Deploy Local Network Gateway template
  template:
    src: localnetwork_gw.tf.j2
    dest: "{{ terraform_output_dir }}/localnetwork_gw.tf"
    owner: root
    group: root
    mode: 0644

- name: Deploy Availability Set
  template:
    src: availability_set.tf.j2
    dest: "{{ terraform_output_dir }}/availability_set.tf"
    owner: root
    group: root
    mode: 0644

- name: Deploy Apache role from template
  template:
    src: template.tf.j2
    dest: "{{ terraform_output_dir }}/apache.tf"
    owner: root
    group: root
    mode: 0644
  vars:
    group: apache

- name: Deploy HAProxy role from template
  template:
    src: template.tf.j2
    dest: "{{ terraform_output_dir }}/haproxy.tf"
    owner: root
    group: root
    mode: 0644
  vars:
    group: haproxy

- name: Deploy Nginx role from template
  template:
    src: template.tf.j2
    dest: "{{ terraform_output_dir }}/nginx.tf"
    owner: root
    group: root
    mode: 0644
  vars:
    group: nginx

- name: Deploy Application Server role from template
  template:
    src: template.tf.j2
    dest: "{{ terraform_output_dir }}/appserver.tf"
    owner: root
    group: root
    mode: 0644
  vars:
    group: appserver

- name: Deploy Redis role from template
  template:
    src: template.tf.j2
    dest: "{{ terraform_output_dir }}/redis.tf"
    owner: root
    group: root
    mode: 0644
  vars:
    group: redis

- name: Deploy Elastic role from template
  template:
    src: template.tf.j2
    dest: "{{ terraform_output_dir }}/elastic.tf"
    owner: root
    group: root
    mode: 0644
  vars:
    group: elastic

- name: Deploy MySQL" role from template
  template:
    src: template.tf.j2
    dest: "{{ terraform_output_dir }}/mysql.tf"
    owner: root
    group: root
    mode: 0644
  vars:
    group: mysql

- name: Deploy RabbitMQ role from template
  template:
    src: template.tf.j2
    dest: "{{ terraform_output_dir }}/rabbitmq.tf"
    owner: root
    group: root
    mode: 0644
  vars:
    group: rabbitmq

- name: Deploy Zabbix role from template
  template:
    src: template.tf.j2
    dest: "{{ terraform_output_dir }}/zabbixproxy.tf"
    owner: root
    group: root
    mode: 0644
  vars:
    group: zabbixproxy

- name: Deploy Kannel role from template
  template:
    src: template.tf.j2
    dest: "{{ terraform_output_dir }}/kannel.tf"
    owner: root
    group: root
    mode: 0644
  vars:
    group: kannel
